### ISSUE TITLE
Legend does not return any Marker 

### ISSUE THREAD

**Issue by FaberDC** [NewGuy012/spider_plot#3]
Hi, 

I thank you for your hard work. The spider_plot is very amazing !

I would notice a little bug. Unfortunately, no one between spider_plot, spider_plot_R2019b, and spider_plot_class allows returning a legend with the markers in Matlab R2020b. For example, if you run this code:

```
 D1 = [5 3 9 1 2];   
D2 = [5 8 7 2 9];
D3 = [8 2 1 4 6];
P = [D1; D2; D3];

% Spider plot
spider_plot(P);

% Legend settings
legend('D1', 'D2', 'D3', 'Location', 'southoutside');
```

The legend shows only the colored lines without markers. If you try customized markers the result is the same. 
Could you suggest something to fix this issue? 

Thank you for any suggestions.
Best Regards
FDC

**Comment by NewGuy012** [comment]
Hi FaberDC, thanks for finding that bug! I will be releasing a fix for that shortly.

**Comment by NewGuy012** [comment]
Hi FaberDC, it should be fixed in the latest update. Thanks!

**Comment by waqasahmad531** [comment]
Hi, 

I think the problem still exists: Following working code gives me legend without markers: 
`D1 = [5 3 9 1 2];
D2 = [5 8 7 2 9];
D3 = [8 2 1 4 6];
P = [D1; D2; D3];
% Spider plot
spider_plot(P,...
'AxesInterval', 4,...
'AxesPrecision', 0,...
'AxesLabelsOffset', 0.1,...
'AxesDisplay', 'one',...
'AxesScaling', 'linear',...
'FillOption', {'on'},...
'AxesFontSize', 12,...
'AxesOffset', 1,...
'AxesZoom', 0.7,...
'AxesHorzAlign', 'center',...
'AxesVertAlign', 'middle',...
'LineStyle', {'-.','--','--'},...
'LineWidth', [0.5,0.7,1],...
'LineTransparency', 0.5,...
'Marker', {'o', 'd', 's'},...
'LabelFontSize', 13,...
'FillTransparency', [0.01 0.05 0.075]);`

Looking forward to the solution.

Thanks

**Comment by NewGuy012** [comment]
Hi @waqasahmad531, which version are you using? This is what I get using the latest version (v17.1) with the code above.

![untitled](https://user-images.githubusercontent.com/22648054/148664730-34a2d5f8-f717-4733-a1a1-88e6019e3819.png)

**Comment by waqasahmad531** [comment]
> Hi @waqasahmad531, which version are you using? This is what I get using the latest version (v17.1) with the code above.
> 
> ![untitled](https://user-images.githubusercontent.com/22648054/148664730-34a2d5f8-f717-4733-a1a1-88e6019e3819.png)

Yes you are right. I updated the package again and it worked fine. Thank you.
